config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users, path_names: { sign_in: 'login' }
  get :privacy, to: 'pages#privacy', as: :privacy
  get :contact, to: 'pages#contact'
  post :contact, to: 'pages#mail_contact'
  get :services, to: 'pages#services'
  resources :projects, only: %i[index show]
  namespace :admin do
    authenticate :user, ->(user) { user.admin? } do
      resources :projects do
        member do
          patch 'publish', to: 'projects#publish'
        end
      end
      resources :services
    end
    authenticated do
      root to: 'projects#index'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_one_attached :banner
  has_many_attached :photos
  has_many :project_services, dependent: :destroy
  has_many :services, through: :project_services
  validates :banner, attached: true
  extend FriendlyId
  friendly_id :name, use: :slugged

  def affiliates
    [location, client, architect, contractor]
  end

  def affiliates_hash
    { location: location, client: client, architect: architect, contractor: contractor}
  end

  def services_sentence
    names = services.map {|s| s.title}
    names.join(" | ")
  end
end

app/models/project_service.rb
class ProjectService < ApplicationRecord
  belongs_to :service
  belongs_to :project
end

app/models/service.rb
class Service < ApplicationRecord
  has_rich_text :content
  has_one_attached :photo
  has_many :project_services, dependent: :destroy
  has_many :projects, through: :project_services
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_action :find_project, only: %i[show edit update destroy publish]

  def index
    @projects = Project.all
    @element_height = "250px"
    @sm_count = 1
    @md_count = 3
    @lg_count = 3
    @xl_count = 3
    @ms_per_scroll = 4000
  end

  def show
    @projects = Project.all
    @element_height = "250px"
    @sm_count = 1
    @md_count = 3
    @lg_count = 3
    @xl_count = 3
    @ms_per_scroll = 4000
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to admin_project_path(@project)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to admin_project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to admin_projects_path
  end

  def publish
    @project.update(published: !@project.published)
    redirect_to admin_project_path(@project)
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :location, :client, :architect, :sub_header, :contractor, :content, :banner, photos: [], service_ids: [])
  end
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < ApplicationController
  before_action :find_service, only: %i[show edit update destroy publish]

  def index
    @services = Service.all
  end

  def show
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    if @service.save
      redirect_to admin_services_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @service.update(service_params)
      redirect_to admin_services_path()
    else
      render :edit
    end
  end

  def destroy
    @service.destroy
    redirect_to admin_services_path
  end

  private

  def find_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:title, :content, :photo, :color)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :mail_contact, :privacy, :services, :contact ]

  def home
    @projects = Project.where(published: true).first(6)
    @element_height = "400px"
    @sm_count = 1
    @md_count = 3
    @lg_count = 3
    @xl_count = 3
    @ms_per_scroll = 4000
  end

  def mail_contact
    # blob = ActiveStorage::Blob.create_after_upload!(
    #   io: params.dig(:contact, :attachment),
    #   filename: "#{Time.now.strftime('%Y%m%d')}",
    #   content_type: params.dig(:contact, :attachment).content_type
    # )
    ContactMailer.with(
      name: params.dig(:contact, :name),
      email: params.dig(:contact, :email),
      phone: params.dig(:contact, :phone),
      location: params.dig(:contact, :location),
      message: params.dig(:contact, :message),
      attachment: params.dig(:contact, :attachment),
    ).contact.deliver_now
    raise
  end

  def services
    @services = Service.all
  end

  def privacy
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @projects = Project.includes(:services).where(published: true).shuffle
  end

  def show
    @project = Project.friendly.find(params[:id])
    @projects = Project.includes(:services).where(published: true).where.not(id: @project.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/projects/_form.html.erb
<div class="container pv-30">
  <div class="row">
    <div class="col-xs-12 col-sm-8 offset-sm-2">
      <div class="form-post">
        <h1>New Project</h1>
        <%= simple_form_for [:admin, project] do |f| %>
          <%= f.input :name %>
          <%= f.input :sub_header %>
          <%= f.input :location %>
          <%= f.input :client %>
          <%= f.input :architect %>
          <%= f.input :contractor %>
          <%#= f.association :categories, as: :check_boxes %>
          <div class="form-group">
            <label class="control-label check_boxes optional">Services</label>
            <input type="hidden" name="project[service_ids][]" value="">
            <div class="category-choices">
              <% Service.all.each do |service| %>
                <input type="checkbox" class="hidden" value="<%= service.id %>" name="project[service_ids][]" id="project_service_ids_<%= service.id %>" <%= "checked" if project.service_ids.include?(service.id) %>>
                <label class="category-choice <%= "active" if project.service_ids.include?(service.id) %>" for="project_service_ids_<%= service.id %>" style="background-color: #<%= service.color %>">
                  <%= service.title %>
                  <i class="fa fa-check"></i>
                </label>
              <% end %>
             </div>
          </div>
          <%= f.input :banner %>
          <p></p>
          <p>The alphabetical order of the photo file names determines the order in which they will appear</p>
          <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "Photos (max 4)" %>
          <!-- Inject categories here -->
          <%= f.input :content, placeholder: "In this tutorial..." %>
          <%= f.submit class: "btn btn-primary"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/projects/edit.html.erb
<div class="container">
  <%= render 'form', project: @project %>  
</div>

app/views/admin/projects/index.html.erb
<%= link_to "New Project", new_admin_project_path, class: 'btn btn-danger mt5' %>
<%= link_to "Services", admin_services_path, class: 'btn btn-primary mt5' %>

<div class="projects-grid mt5">
  <% @projects.each do |project| %>
    <%= link_to admin_project_path(project), class: "project-card-link" do  %>
      <%= render "shared/project_card", project: project %>
    <% end %>
  <% end %>
</div>

app/views/admin/projects/new.html.erb
<div class="container">
  <%= render 'form', project: @project %>  
</div>

app/views/admin/projects/show.html.erb
<%= render "shared/project", admin: true %>
<%= render "shared/lcar",
  elements: @projects,
  element_height: @element_height,
  sm_count:  @sm_count,
  md_count: @md_count,
  lg_count: @lg_count,
  xl_count: @xl_count,
  ms_per_scroll: @ms_per_scroll,
  full: true
%>

app/views/admin/services/_form.html.erb
<%= simple_form_for [:admin, service] do |f| %>
  <%= f.input :title, placeholder: "Cummon Nev, you must be able to think of a good title..." %>
  <%= f.input :color, placeholder: "Use any HEX color code, without the #, i.e. F2F2F2" %>
  <%= f.input :photo, as: :file %>
  <%= f.text_area :content, placeholder: "This service offers the following things...", class: "high-input" %>
  <%= f.submit class: "btn btn-primary"  %>
<% end %>

app/views/admin/services/edit.html.erb
<div class="container pv-30">
  <div class="row">
    <div class="col-xs-12 col-sm-8 offset-sm-2">
      <div class="form-post">
        <h1>Edit Service</h1>
        <%= render "form", service: @service %>
      </div>
    </div>
  </div>
</div>

app/views/admin/services/index.html.erb
<div class="seven-container">
  <%= link_to "New Service", new_admin_service_path, class: "btn btn-danger mt5" %>
  <%= link_to "Projects", admin_projects_path, class: "btn btn-primary mt5" %>
  <%= render "shared/services", services: @services, admin: true %>
</div>

app/views/admin/services/new.html.erb
<div class="container pv-30">
  <div class="row">
    <div class="col-xs-12 col-sm-8 offset-sm-2">
      <div class="form-post">
        <h1>New Service</h1>
        <%= render "form", service: @service %>
      </div>
    </div>
  </div>
</div>

app/views/admin/shared/_lcar_element.html.erb
<% if link_path %>
  <%= link_to link_path,
    class: "element",
    style: "height: #{height};
    width: #{(1 / sm_count) * 100}%;
    background-image: url(#{url_for(element.banner)})" do %>
    <h5><%= element.name %></h5>
    <p><%= element.location %> | <%= element.services_sentence %></p>
  <% end %>
<% else %>
  <div
    class="element"
    style="
      height: <%= height %>;
      width: <%= (1 / sm_count) * 100 %>%;
    ">
    <h5><%= element.name %></h5>
    <p><%= element.location %> | <%= element.services_sentence %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-171717688-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-171717688-2');
    </script>
    <title>Seven Consulting</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Building Simulation, Energy and Sustainability">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="Seven Consulting" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="seven-cover.png" />
    <meta property="og:description" content="Building Simulation, Energy and Sustainability" />
    <meta property="og:site_name" content="www.7consulting.com" />

    <!-- Twitter Card data -->
<!--     <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="www.7consulting.com">
    <meta name="twitter:title" content="Seven Consulting">
    <meta name="twitter:description" content="Building Simulation, Energy and Sustainability">
    <meta name="twitter:creator" content="nev">
    <meta name="twitter:image:src" content="seven-cover.png"> -->

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/ea437f64d7.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= javascript_pack_tag 'application', defer: true %>
    <%= yield :head %>

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="min-height">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="devise-wrapper">
  <div class="top-banner" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,1)), url(<%= asset_path('seven-main.jpg') %>); background-size: cover; background-position: center;">
    <div class="banner-text">
      <h1 class="text-center"><strong>CONTACT</strong></h1>
      <h5 class="text-center">Please feel free to contact Seven Consulting if you have any questions about how we can help your project.</h5>
    </div>
  </div>
  <div class="row" style="max-width: 1220px;margin: 0 auto;padding-top: 5vh;">
    <div class="col-sm-12 col-md-6">
      <div class="devise-form">
        <h3 class="text-center mb-4 dark-blue">Leave us a message</h3>
        <%= simple_form_for :contact, url: contact_path, method: :post, html: { class: "contact-form" } do |f| %>
          <div class="form-inputs">
            <%= f.input :name, required: false, input_html: { class: "devise-input" }, placeholder: "Your name", label: false %>
            <%= f.input :email, required: false, input_html: { class: "devise-input" }, placeholder: "Your email", label: false %>
          </div>
          <div class="form-inputs">
            <%= f.input :phone, required: false, input_html: { class: "devise-input" }, placeholder: "Your phone number", label: false %>
            <%= f.input :location, required: false, input_html: { class: "devise-input" }, placeholder: "Project location", label: false %>
          </div>
          <%= f.input :message, as: :text, required: false, input_html: { class: "devise-input place", rows: 10 }, label: false, placeholder: "Tell us about your project"  %>
          <%= f.input :attachment, as: :file, required: false %>
          <%= f.button :submit, "SEND", class: "seven-button devise-button mb-4" %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-12 col-md-6 text-center pt20">
      <h3 class="text-center mb-4 dark-blue">Call or email us</h3>
      <p class="m-0">+44(0)161 209 3259</p>
      <p class="mb-5"><a href="mailto:nev@7consulting.co.uk">nev@7consulting.co.uk</a></p>
      <h3 class="text-center mb-4 dark-blue">Or find us at</h3>
      <p class="m-0">Seven Consulting</p>
      <p class="m-0">Peter House,</p>
      <p class="m-0">Oxford Street,</p>
      <p class="m-0">Manchester,</p>
      <p class="m-0">M1 5AN</p>
      <div class="img-holder">
        <div class="map-img" style="background-image: url(<%= asset_path('sevenmap.png')%>);)"></div>
      </div>
    </div>


  </div>
</div>

app/views/pages/services.html.erb
<%= render "shared/banner", title: "Services", details: "We offer a range of services for your project from concept design through to building completion and sign off. Ours suite of services ensure you achieve your sustainability ratings, comfort criteria and energy targets", sub: false, url: "serv-bg.webp" %>
<div class="seven-container">
  <%= render "shared/services", admin: false %>

  <%= render 'shared/partners_and_accreditations' %>

</div>

app/views/projects/index.html.erb
<%= render "shared/banner", title: "Projects", details: "We are an established, innovative energy and sustainability consultancy that provide a full suite of modelling and compliance solutions across all sectors of the property and construction industry. We easily integrate into your design team and are experienced in providing solutions that are tailored to your projects specific requirements from planning to project completion. Below is a sample of the projects we have worked in various sectors, from Residential and Hospitality to Healthcare, Commercial and University", sub: nil, url: 'proj-bg.webp' %>
<div class="projects-grid">
  <% @projects.each do |project| %>
    <%= link_to project_path(project), class: "project-card-link" do  %>
      <%= render "shared/project_card", project: project %>
    <% end %>
  <% end %>
</div>

app/views/shared/_banner.html.erb
<div class="top-banner" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0.7)), url(<%= asset_path(url) %>); background-size: cover; background-position: center;">
  <div class="banner-text">
    <h1 class="text-center white"><strong><%= title %></strong></h1>
    <h5 class="text-center white fwnorm"><%= details %></h5>
    <% if sub %>
      <p class="text-center white fwnorm top-b"><%= sub %></p>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer <%= 'proj-footer' if controller_name == 'projects' && action_name == 'show' %>">
  <div class="container">
    <%= image_tag 'seven.svg', class: 'seven-logo' %>
    <div class="footer-info-container">
      <div class="footer-info mb-4">
        <div class="footer-info-address mr-5">
          <p class="bold footer-title">MANCHESTER</p>
          <p class="m-0">Seven Consulting</p>
          <p class="m-0">Peter House,</p>
          <p class="m-0">Oxford Street,</p>
          <p class="m-0">Manchester,</p>
          <p class="m-0">M1 5AN</p>
        </div>
        <div class="footer-info-links">
          <p class="bold footer-title">USEFUL LINKS</p>
          <%= link_to 'Privacy Policy', privacy_path, class: 'footer-link' %>
          <%= link_to 'Contact', contact_path, class: 'footer-link' %>
          <%= link_to 'Admin', admin_projects_path, class: 'footer-link' %>
          <% if current_user %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
          <% end %>
        </div>
      </div>
      <div class="footer-contact">
        <p class="m-0">Tel: +44(0)161 209 3259</p>
        <p class="m-0">Email: nev@7consulting.co.uk</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="nav-cont <%= 'proj-footer' if controller_name == 'projects' && action_name == 'show' %>">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon ">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "seven.svg", class: 'seven-logo' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item flex-center active">
          <%= link_to "HOME", root_path, class: "nav-link white-imp flex-lm" %>
        </li>
        <li class="nav-item flex-center active">
          <%= link_to "SERVICES", services_path, class: "nav-link white-imp flex-lm" %>
        </li>
        <li class="nav-item flex-center active">
          <%= link_to "PROJECTS", projects_path, class: "nav-link white-imp flex-lm" %>
        </li>
<!--         <li class="nav-item flex-center active">
          <%= link_to "ACADEMY", "http://sevenacademy.co.uk/", class: "nav-link white-imp flex-lm", target: "_blank" %>
        </li> -->
        <li class="nav-item flex-center active">
          <%= link_to "CONTACT", contact_path, class: "nav-link white-imp flex-lm" %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_project.html.erb
<div class="top-banner" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,1)), url(<%= url_for(@project.banner) %>);">
  <div class="banner-text text-center">
    <h1 class="banner-title"><strong><%= @project.name %></strong></h1>
    <h5 class="banner-details text-center"><%= @project.sub_header %></h5>
  </div>
</div>
<div class="seven-container proj-show">

  <% if admin %>
    <div style="padding: 10px;">
      <%= link_to @project.published ? 'Unpublish' : 'Publish' , publish_admin_project_path(@project), method: :patch, class: "btn #{@project.published ? 'btn-danger' : 'btn-primary'}" %>
      <%= link_to "Edit", edit_admin_project_path(@project), class: "btn btn-primary" %>
    </div>
  <% end %>
  <div class="row noh">
    <div class="col-sm-12 col-md-3">
      <div class="mp  mid-lpad">
        <% @project.affiliates_hash.each do |affiliate, value| %>
          <% if value.present? %>
            <h5 class="proj-atts"><%= affiliate.upcase %></h5>
            <p><%= value %></p>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-sm-12 col-md-6 proj-content">
      <div class="mp hpm">
        <%= simple_format @project.content %>
      </div>
    </div>
    <div class="col-sm-12 col-md-3">
      <div class="mp mid-lpad">
        <h5 class="proj-atts">SERVICES PROVIDED</h5>
        <% @project.services.each do |service| %>
          <div class="service-block" style="background-color: #<%= service.color %>;">
            <% if service.photo.attached? %>
              <%= image_tag url_for(service.photo), class: "service-svg-small sp", alt: "seven.svg" %>
            <% else %>
              <%= image_tag image_path("seven.svg"), class: "service-svg-small sp" %>
            <% end %>
            <h5><%= service.title %></h5>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="project-photos">
    <% @project.photos.attachments.each do |photo| %>
      <%= render "shared/project_photo", photo: photo %>
    <% end %>
  </div>
</div>

app/views/shared/_services.html.erb
<div class="container override-container">
  <div class="row noh pt20" style="max-width: 1220px;margin: 0 auto;">
    <% @services.each do |service| %>
      <div class="col-sm-12 col-md-6 p20" >
        <div class="service" style="background-color: #<%= service.color %>;" id="<%= service.title.downcase[0..2] %>">
          <% if service.photo.attached? %>
            <%= image_tag url_for(service.photo), class: "service-svg" %>
          <% end %>
          <h2>
            <%= service.title %>
            <% if admin %>
              <%= link_to edit_admin_service_path(service) do %>
                <i class="fas fa-edit" style="color: white;"></i>
              <% end %>
            <% end %>
          </h2>
          <%= service.content %>
        </div>
      </div>
    <% end %>
  </div>
</div>